# Alacritty config
[general]
import = ["~/.config/alacritty/gruvbox.toml"]

[window]
decorations = "None"
padding.x = 0
padding.y = 0
opacity = 1.0

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 32.0

[mouse]
hide_when_typing = false

[cursor]
style = { shape = "Block", blinking = "Never" }
